import type { OwnedWatch } from '@/types/watch'

export const SEEDED_OWNED_WATCHES: OwnedWatch[] = [
  {
    id: 'owned-seed-1',
    watchId: 'longines-legend-diver-white',
    condition: 'Like New',
    purchaseDate: '2023-09-01',
    purchasePrice: 1180,
    notes: 'AD purchase, complete set',
    ownershipStatus: 'Owned',
    slot: 0,
  },
  {
    id: 'owned-seed-2',
    watchId: 'longines-legend-diver-blue',
    condition: 'Unworn',
    purchaseDate: '2024-02-01',
    purchasePrice: 1220,
    notes: 'Birthday gift, unworn',
    ownershipStatus: 'Recently Added',
    slot: 1,
  },
  {
    id: 'owned-seed-3',
    watchId: 'longines-legend-diver-green',
    condition: 'Excellent',
    purchaseDate: '2022-11-01',
    purchasePrice: 1100,
    notes: 'Limited run, hard to find',
    ownershipStatus: 'For Sale',
    slot: 2,
  },
  {
    id: 'owned-seed-4',
    watchId: 'longines-legend-diver-black',
    condition: 'Good',
    purchaseDate: '2021-06-01',
    purchasePrice: 980,
    notes: 'Leather strap original',
    ownershipStatus: 'Needs Service',
    slot: 3,
  },
  {
    id: 'owned-seed-5',
    watchId: 'longines-legend-diver-grey',
    condition: 'Excellent',
    purchaseDate: '2023-04-01',
    purchasePrice: 1150,
    notes: 'Odd dial - love the patina feel',
    ownershipStatus: 'Owned',
    slot: 4,
  },
]
