// Loader for the curated strap-template catalog (data/strap-templates.json).
//
// Templates are the photorealistic, Delugs-style master images generated by
// scripts/generate-strap-images.ts and uploaded to the `strap-images` Supabase
// bucket. They power the "Quick pick from common straps" section of the Add Strap
// modal (and the future Strap Studio). `imageUrl` is empty until the generation
// script has run + uploaded; callers fall back to the CSS swatch in that case.

import rawTemplates from '@/data/strap-templates.json'
import { withVersion } from '@/lib/watchImages/cacheBust'
import type { StrapMaterial, StrapStyle } from '@/types/watch'

export interface StrapTemplate {
  id: string
  material: StrapMaterial
  subMaterial: string
  color: string
  colorHex: string
  style: StrapStyle
  /** Public Supabase Storage URL, cache-busted via withVersion(); '' if not generated yet. */
  imageUrl: string
  availableLugWidths: number[]
  affiliatePartner: string | null
  affiliateUrl: string | null
}

const TEMPLATES: StrapTemplate[] = (rawTemplates as StrapTemplate[]).map((t) => ({
  ...t,
  imageUrl: t.imageUrl ? withVersion(t.imageUrl) ?? '' : '',
}))

/** All templates, in catalog order. */
export function getStrapTemplates(): StrapTemplate[] {
  return TEMPLATES
}

/** Templates grouped by material (for the tabbed quick-pick picker). */
export function getTemplatesByMaterial(): Array<{ material: StrapMaterial; templates: StrapTemplate[] }> {
  const order: StrapMaterial[] = []
  const byMaterial = new Map<StrapMaterial, StrapTemplate[]>()
  for (const t of TEMPLATES) {
    if (!byMaterial.has(t.material)) {
      byMaterial.set(t.material, [])
      order.push(t.material)
    }
    byMaterial.get(t.material)!.push(t)
  }
  return order.map((material) => ({ material, templates: byMaterial.get(material)! }))
}

export function findTemplate(id: string): StrapTemplate | undefined {
  return TEMPLATES.find((t) => t.id === id)
}

const norm = (s: string | undefined | null) => (s ?? '').trim().toLowerCase()

/**
 * Best-matching template photo URL for a (material, subMaterial, color) spec — used as the
 * imagery fallback wherever a strap has no photo of its own, so the UI shows a real picture
 * instead of a drawn swatch. Falls back through progressively looser matches; returns undefined
 * only when no template of that material exists (callers then show a neutral placeholder).
 */
export function findTemplatePhoto(
  material: string,
  subMaterial?: string | null,
  color?: string | null,
): string | undefined {
  const withImg = TEMPLATES.filter((t) => t.imageUrl)
  const m = norm(material), sub = norm(subMaterial), col = norm(color)
  const tiers = [
    (t: StrapTemplate) => norm(t.material) === m && norm(t.subMaterial) === sub && norm(t.color) === col,
    (t: StrapTemplate) => norm(t.material) === m && norm(t.color) === col,
    (t: StrapTemplate) => norm(t.material) === m && norm(t.subMaterial) === sub,
    (t: StrapTemplate) => norm(t.material) === m,
  ]
  for (const match of tiers) {
    const hit = withImg.find(match)
    if (hit) return hit.imageUrl
  }
  return undefined
}
