import type { Watch } from '@/types/watch'

export const watches: Watch[] = [
  {
    id: 'longines-ld-white',
    brand: 'Longines',
    model: 'Legend Diver',
    reference: 'L3.764.4.16.6',
    caseSizeMm: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'White',
    movement: 'L888.4 (Auto)',
    complications: ['Date'],
    condition: 'Like New',
    purchaseDate: '2023-09-01',
    purchasePrice: 1180,
    estimatedValue: 1350,
    notes: 'AD purchase, complete set',
    imageUrl: '/watches/longines-05.avif',
    dialConfig: { dialColor: '#F5F0E8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Diver',
    ownershipStatus: 'Owned',
  },
  {
    id: 'longines-ld-navy',
    brand: 'Longines',
    model: 'Legend Diver',
    reference: 'L3.764.4.96.6',
    caseSizeMm: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Navy Blue',
    movement: 'L888.4 (Auto)',
    complications: ['Date'],
    condition: 'Unworn',
    purchaseDate: '2024-02-01',
    purchasePrice: 1220,
    estimatedValue: 1380,
    notes: 'Birthday gift, unworn',
    imageUrl: '/watches/longines-02.avif',
    dialConfig: { dialColor: '#1B2A4A', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
    ownershipStatus: 'Recently Added',
  },
  {
    id: 'longines-ld-green',
    brand: 'Longines',
    model: 'Legend Diver',
    reference: 'L3.764.4.06.6',
    caseSizeMm: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Forest Green',
    movement: 'L888.4 (Auto)',
    complications: ['Date'],
    condition: 'Excellent',
    purchaseDate: '2022-11-01',
    purchasePrice: 1100,
    estimatedValue: 1450,
    notes: 'Limited run, hard to find',
    imageUrl: '/watches/longines-03.avif',
    dialConfig: { dialColor: '#2A4A2E', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
    ownershipStatus: 'For Sale',
  },
  {
    id: 'longines-ld-black',
    brand: 'Longines',
    model: 'Legend Diver',
    reference: 'L3.764.4.50.0',
    caseSizeMm: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'L888.4 (Auto)',
    complications: ['Date'],
    condition: 'Good',
    purchaseDate: '2021-06-01',
    purchasePrice: 980,
    estimatedValue: 1250,
    notes: 'Leather strap original',
    imageUrl: '/watches/longines-04.avif',
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
    ownershipStatus: 'Needs Service',
  },
  {
    id: 'longines-ld-grey',
    brand: 'Longines',
    model: 'Legend Diver',
    reference: 'L3.764.4.99.6',
    caseSizeMm: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Grey Anthracite',
    movement: 'L888.4 (Auto)',
    complications: ['Date'],
    condition: 'Excellent',
    purchaseDate: '2023-04-01',
    purchasePrice: 1150,
    estimatedValue: 1340,
    notes: 'Odd dial — love the patina feel',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#5A5A5A', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
    ownershipStatus: 'Owned',
  },
  {
    id: 'rolex-submariner-date',
    brand: 'Rolex',
    model: 'Submariner Date',
    reference: '126610LN',
    caseSizeMm: 41,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Calibre 3235',
    complications: ['Date'],
    condition: 'Excellent',
    purchaseDate: '2021-08-14',
    purchasePrice: 9800,
    estimatedValue: 12200,
    notes: 'Classic no-date bezel insert',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
    ownershipStatus: 'Owned',
  },
  {
    id: 'rolex-gmt-master-ii-pepsi',
    brand: 'Rolex',
    model: 'GMT-Master II',
    reference: '126710BLRO',
    caseSizeMm: 40,
    caseMaterial: 'Oystersteel',
    dialColor: 'Black',
    movement: 'Calibre 3285',
    complications: ['Date', 'GMT'],
    condition: 'Like New',
    purchaseDate: '2022-03-20',
    purchasePrice: 11200,
    estimatedValue: 16900,
    notes: 'Jubilee bracelet',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'GMT',
    ownershipStatus: 'For Sale',
  },
  {
    id: 'rolex-daytona-white',
    brand: 'Rolex',
    model: 'Cosmograph Daytona',
    reference: '116500LN',
    caseSizeMm: 40,
    caseMaterial: 'Oystersteel',
    dialColor: 'White',
    movement: 'Calibre 4130',
    complications: ['Chronograph'],
    condition: 'Good',
    purchaseDate: '2019-06-11',
    purchasePrice: 18500,
    estimatedValue: 27500,
    notes: 'Cerachrom bezel',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Chronograph',
    ownershipStatus: 'Owned',
  },
  {
    id: 'rolex-explorer-i',
    brand: 'Rolex',
    model: 'Explorer',
    reference: '124270',
    caseSizeMm: 36,
    caseMaterial: 'Oystersteel',
    dialColor: 'Black',
    movement: 'Calibre 3230',
    complications: [],
    condition: 'Like New',
    purchaseDate: '2023-01-06',
    purchasePrice: 6900,
    estimatedValue: 7600,
    notes: 'Compact 36mm proportions',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Field',
    ownershipStatus: 'Recently Added',
  },
  {
    id: 'rolex-datejust-blue',
    brand: 'Rolex',
    model: 'Datejust 41',
    reference: '126334',
    caseSizeMm: 41,
    caseMaterial: 'Steel / White Gold',
    dialColor: 'Blue',
    movement: 'Calibre 3235',
    complications: ['Date'],
    condition: 'Excellent',
    purchaseDate: '2020-10-02',
    purchasePrice: 9200,
    estimatedValue: 10800,
    notes: 'Fluted bezel, Jubilee',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Dress',
    ownershipStatus: 'Needs Service',
  },
  {
    id: 'omega-speedmaster-moonwatch',
    brand: 'Omega',
    model: 'Speedmaster Professional',
    reference: '310.30.42.50.01.001',
    caseSizeMm: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Calibre 3861',
    complications: ['Chronograph'],
    condition: 'Excellent',
    purchaseDate: '2021-12-15',
    purchasePrice: 6100,
    estimatedValue: 7200,
    notes: 'Hesalite crystal',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Chronograph',
    ownershipStatus: 'Owned',
  },
  {
    id: 'omega-seamaster-300m-blue',
    brand: 'Omega',
    model: 'Seamaster Diver 300M',
    reference: '210.30.42.20.03.001',
    caseSizeMm: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Calibre 8800',
    complications: ['Date'],
    condition: 'Like New',
    purchaseDate: '2024-05-09',
    purchasePrice: 5400,
    estimatedValue: 5900,
    notes: 'Wave dial',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
    ownershipStatus: 'Recently Added',
  },
  {
    id: 'omega-aqua-terra-green',
    brand: 'Omega',
    model: 'Seamaster Aqua Terra',
    reference: '220.10.41.21.10.001',
    caseSizeMm: 41,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Green',
    movement: 'Calibre 8900',
    complications: ['Date'],
    condition: 'Unworn',
    purchaseDate: '2025-02-22',
    purchasePrice: 5800,
    estimatedValue: 6100,
    notes: 'Teak patterned dial',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#2F5A3A', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Sport',
    ownershipStatus: 'For Sale',
  },
  {
    id: 'omega-railmaster-grey',
    brand: 'Omega',
    model: 'Railmaster',
    reference: '220.10.40.20.06.001',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Grey',
    movement: 'Calibre 8806',
    complications: [],
    condition: 'Good',
    purchaseDate: '2018-09-30',
    purchasePrice: 3900,
    estimatedValue: 4200,
    notes: 'Anti-magnetic movement',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#6F6F6F', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Field',
    ownershipStatus: 'Needs Service',
  },
  {
    id: 'omega-constellation-silver',
    brand: 'Omega',
    model: 'Constellation Globemaster',
    reference: '130.30.39.21.02.001',
    caseSizeMm: 39,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Calibre 8900',
    complications: ['Date'],
    condition: 'Excellent',
    purchaseDate: '2020-04-19',
    purchasePrice: 5700,
    estimatedValue: 6400,
    notes: 'Pie-pan dial inspiration',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Dress',
    ownershipStatus: 'Owned',
  },
  {
    id: 'patek-nautilus-blue',
    brand: 'Patek Philippe',
    model: 'Nautilus',
    reference: '5711/1A-010',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Calibre 26-330 S C',
    complications: ['Date'],
    condition: 'Like New',
    purchaseDate: '2019-11-03',
    purchasePrice: 34000,
    estimatedValue: 50000,
    notes: 'Discontinued icon',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Integrated Bracelet',
    ownershipStatus: 'Owned',
  },
  {
    id: 'patek-aquanaut-black',
    brand: 'Patek Philippe',
    model: 'Aquanaut',
    reference: '5167A-001',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Calibre 324 S C',
    complications: ['Date'],
    condition: 'Excellent',
    purchaseDate: '2022-07-18',
    purchasePrice: 26000,
    estimatedValue: 36000,
    notes: 'Tropical strap',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Sport',
    ownershipStatus: 'For Sale',
  },
  {
    id: 'patek-calatrava-ivory',
    brand: 'Patek Philippe',
    model: 'Calatrava',
    reference: '6119R-001',
    caseSizeMm: 39,
    caseMaterial: 'Rose Gold',
    dialColor: 'Ivory',
    movement: 'Calibre 30-255 PS',
    complications: [],
    condition: 'Unworn',
    purchaseDate: '2025-01-10',
    purchasePrice: 33000,
    estimatedValue: 36500,
    notes: 'Hobnail bezel',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Dress',
    ownershipStatus: 'Recently Added',
  },
  {
    id: 'patek-world-time-blue',
    brand: 'Patek Philippe',
    model: 'World Time',
    reference: '5230P-001',
    caseSizeMm: 38,
    caseMaterial: 'Platinum',
    dialColor: 'Blue',
    movement: 'Calibre 240 HU',
    complications: ['World Time'],
    condition: 'Excellent',
    purchaseDate: '2021-06-01',
    purchasePrice: 41000,
    estimatedValue: 46500,
    notes: 'Hand-guilloché center',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'GMT',
    ownershipStatus: 'Owned',
  },
  {
    id: 'patek-golden-ellipse',
    brand: 'Patek Philippe',
    model: 'Golden Ellipse',
    reference: '5738R-001',
    caseSizeMm: 39,
    caseMaterial: 'Rose Gold',
    dialColor: 'Blue',
    movement: 'Calibre 240',
    complications: [],
    condition: 'Good',
    purchaseDate: '2017-03-26',
    purchasePrice: 19000,
    estimatedValue: 22000,
    notes: 'Slim elegant case',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Vintage',
    ownershipStatus: 'Needs Service',
  },
  {
    id: 'lange-zeitwerk',
    brand: 'A. Lange & Söhne',
    model: 'Zeitwerk',
    reference: '142.031',
    caseSizeMm: 42,
    caseMaterial: 'White Gold',
    dialColor: 'Black',
    movement: 'L043.1',
    complications: ['Power Reserve'],
    condition: 'Excellent',
    purchaseDate: '2020-08-08',
    purchasePrice: 47000,
    estimatedValue: 50000,
    notes: 'Jumping digital time',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Dress',
    ownershipStatus: 'Owned',
  },
  {
    id: 'lange-lange1',
    brand: 'A. Lange & Söhne',
    model: 'Lange 1',
    reference: '191.032',
    caseSizeMm: 38,
    caseMaterial: 'White Gold',
    dialColor: 'Silver',
    movement: 'L121.1',
    complications: ['Date', 'Power Reserve'],
    condition: 'Like New',
    purchaseDate: '2023-05-12',
    purchasePrice: 39000,
    estimatedValue: 43000,
    notes: 'Asymmetric dial layout',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Dress',
    ownershipStatus: 'For Sale',
  },
  {
    id: 'lange-saxonia-thin',
    brand: 'A. Lange & Söhne',
    model: 'Saxonia Thin',
    reference: '205.086',
    caseSizeMm: 39,
    caseMaterial: 'Pink Gold',
    dialColor: 'Blue',
    movement: 'L093.1',
    complications: [],
    condition: 'Unworn',
    purchaseDate: '2024-10-04',
    purchasePrice: 22000,
    estimatedValue: 24000,
    notes: 'Ultra-thin manually wound',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Dress',
    ownershipStatus: 'Recently Added',
  },
  {
    id: 'lange-odysseus-grey',
    brand: 'A. Lange & Söhne',
    model: 'Odysseus',
    reference: '363.179',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Grey',
    movement: 'L155.1',
    complications: ['Date', 'Day'],
    condition: 'Excellent',
    purchaseDate: '2022-12-02',
    purchasePrice: 36000,
    estimatedValue: 42000,
    notes: 'Integrated bracelet sports model',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#6F6F6F', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Integrated Bracelet',
    ownershipStatus: 'Owned',
  },
  {
    id: 'lange-1815-chronograph',
    brand: 'A. Lange & Söhne',
    model: '1815 Chronograph',
    reference: '414.028',
    caseSizeMm: 39,
    caseMaterial: 'Pink Gold',
    dialColor: 'Black',
    movement: 'L951.5',
    complications: ['Chronograph'],
    condition: 'Good',
    purchaseDate: '2016-02-17',
    purchasePrice: 42000,
    estimatedValue: 45500,
    notes: 'Column-wheel chronograph',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Chronograph',
    ownershipStatus: 'Needs Service',
  },
  {
    id: 'iwc-mark-xx-blue',
    brand: 'IWC',
    model: 'Pilot\'s Watch Mark XX',
    reference: 'IW328203',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Calibre 32111',
    complications: ['Date'],
    condition: 'Like New',
    purchaseDate: '2024-03-08',
    purchasePrice: 4200,
    estimatedValue: 4900,
    notes: '120h power reserve',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Pilot',
    ownershipStatus: 'Owned',
  },
  {
    id: 'iwc-big-pilot',
    brand: 'IWC',
    model: 'Big Pilot\'s Watch 43',
    reference: 'IW329301',
    caseSizeMm: 43,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Calibre 82100',
    complications: [],
    condition: 'Excellent',
    purchaseDate: '2022-08-15',
    purchasePrice: 6900,
    estimatedValue: 7600,
    notes: 'Oversized crown',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Pilot',
    ownershipStatus: 'For Sale',
  },
  {
    id: 'iwc-portugieser-chrono',
    brand: 'IWC',
    model: 'Portugieser Chronograph',
    reference: 'IW371606',
    caseSizeMm: 41,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Calibre 69355',
    complications: ['Chronograph'],
    condition: 'Unworn',
    purchaseDate: '2025-03-14',
    purchasePrice: 6900,
    estimatedValue: 7300,
    notes: 'Blue feuille hands',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Chronograph',
    ownershipStatus: 'Recently Added',
  },
  {
    id: 'iwc-ingenieur-aqua',
    brand: 'IWC',
    model: 'Ingenieur Automatic 40',
    reference: 'IW328901',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Aqua Blue',
    movement: 'Calibre 32111',
    complications: ['Date'],
    condition: 'Like New',
    purchaseDate: '2024-09-03',
    purchasePrice: 11800,
    estimatedValue: 12600,
    notes: 'Genta-inspired grid dial',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Integrated Bracelet',
    ownershipStatus: 'Owned',
  },
  {
    id: 'iwc-spitfire-bronze',
    brand: 'IWC',
    model: 'Pilot\'s Watch Automatic Spitfire',
    reference: 'IW326805',
    caseSizeMm: 39,
    caseMaterial: 'Bronze',
    dialColor: 'Brown',
    movement: 'Calibre 32110',
    complications: ['Date'],
    condition: 'Good',
    purchaseDate: '2019-05-21',
    purchasePrice: 4200,
    estimatedValue: 4700,
    notes: 'Patina bronze case',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#5A3A26', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Pilot',
    ownershipStatus: 'Needs Service',
  },
  {
    id: 'tudor-black-bay-58',
    brand: 'Tudor',
    model: 'Black Bay 58',
    reference: 'M79030N-0001',
    caseSizeMm: 39,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'MT5402',
    complications: [],
    condition: 'Excellent',
    purchaseDate: '2021-04-28',
    purchasePrice: 3200,
    estimatedValue: 3600,
    notes: 'Riveted bracelet',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
    ownershipStatus: 'Owned',
  },
  {
    id: 'tudor-pelagos-39',
    brand: 'Tudor',
    model: 'Pelagos 39',
    reference: 'M25407N-0001',
    caseSizeMm: 39,
    caseMaterial: 'Titanium',
    dialColor: 'Black',
    movement: 'MT5400',
    complications: [],
    condition: 'Like New',
    purchaseDate: '2023-07-07',
    purchasePrice: 4100,
    estimatedValue: 4500,
    notes: 'Grade 2 titanium case',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
    ownershipStatus: 'Recently Added',
  },
  {
    id: 'tudor-black-bay-gmt',
    brand: 'Tudor',
    model: 'Black Bay GMT',
    reference: 'M79830RB-0010',
    caseSizeMm: 41,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'MT5652',
    complications: ['Date', 'GMT'],
    condition: 'Good',
    purchaseDate: '2019-10-10',
    purchasePrice: 3600,
    estimatedValue: 3900,
    notes: 'Pepsi bezel',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'GMT',
    ownershipStatus: 'For Sale',
  },
  {
    id: 'tudor-ranger',
    brand: 'Tudor',
    model: 'Ranger',
    reference: 'M79950-0001',
    caseSizeMm: 39,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'MT5402',
    complications: [],
    condition: 'Excellent',
    purchaseDate: '2022-06-22',
    purchasePrice: 2850,
    estimatedValue: 3100,
    notes: 'Field-inspired dial',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Field',
    ownershipStatus: 'Owned',
  },
  {
    id: 'tudor-royal-blue',
    brand: 'Tudor',
    model: 'Royal',
    reference: 'M28600-0005',
    caseSizeMm: 41,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'T603',
    complications: ['Date', 'Day'],
    condition: 'Fair',
    purchaseDate: '2018-01-12',
    purchasePrice: 1800,
    estimatedValue: 1950,
    notes: 'Integrated bracelet value pick',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Integrated Bracelet',
    ownershipStatus: 'Needs Service',
  },
  {
    id: 'tag-carrera-chrono',
    brand: 'TAG Heuer',
    model: 'Carrera Chronograph',
    reference: 'CBN2011.BA0642',
    caseSizeMm: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'TH20-00',
    complications: ['Chronograph', 'Date'],
    condition: 'Like New',
    purchaseDate: '2024-01-19',
    purchasePrice: 5600,
    estimatedValue: 6200,
    notes: 'Glassbox profile',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Chronograph',
    ownershipStatus: 'Owned',
  },
  {
    id: 'tag-monaco-blue',
    brand: 'TAG Heuer',
    model: 'Monaco',
    reference: 'CAW211P.FC6356',
    caseSizeMm: 39,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Calibre 11',
    complications: ['Chronograph', 'Date'],
    condition: 'Excellent',
    purchaseDate: '2021-11-12',
    purchasePrice: 5200,
    estimatedValue: 5800,
    notes: 'Square motorsport icon',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Vintage',
    ownershipStatus: 'For Sale',
  },
  {
    id: 'tag-aquaracer-green',
    brand: 'TAG Heuer',
    model: 'Aquaracer Professional 300',
    reference: 'WBP201F.BA0632',
    caseSizeMm: 43,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Green',
    movement: 'Calibre 5',
    complications: ['Date'],
    condition: 'Unworn',
    purchaseDate: '2025-02-02',
    purchasePrice: 3100,
    estimatedValue: 3400,
    notes: 'Ceramic bezel diver',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#2F5A3A', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
    ownershipStatus: 'Recently Added',
  },
  {
    id: 'tag-autavia-gmt',
    brand: 'TAG Heuer',
    model: 'Autavia GMT',
    reference: 'WBE511A.BA0650',
    caseSizeMm: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Calibre 7',
    complications: ['Date', 'GMT'],
    condition: 'Good',
    purchaseDate: '2020-06-06',
    purchasePrice: 3200,
    estimatedValue: 3600,
    notes: 'Bidirectional ceramic bezel',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'GMT',
    ownershipStatus: 'Owned',
  },
  {
    id: 'tag-carrera-date-silver',
    brand: 'TAG Heuer',
    model: 'Carrera Date',
    reference: 'WBN2111.BA0639',
    caseSizeMm: 39,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Calibre 5',
    complications: ['Date'],
    condition: 'Excellent',
    purchaseDate: '2023-03-03',
    purchasePrice: 2400,
    estimatedValue: 2700,
    notes: 'Clean three-hander',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Sport',
    ownershipStatus: 'Needs Service',
  },
  {
    id: 'breitling-navitimer-b01',
    brand: 'Breitling',
    model: 'Navitimer B01 Chronograph 43',
    reference: 'AB0138211B1A1',
    caseSizeMm: 43,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Breitling 01',
    complications: ['Chronograph', 'Date'],
    condition: 'Excellent',
    purchaseDate: '2022-02-14',
    purchasePrice: 7600,
    estimatedValue: 8400,
    notes: 'Slide rule bezel',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Chronograph',
    ownershipStatus: 'Owned',
  },
  {
    id: 'breitling-superocean-blue',
    brand: 'Breitling',
    model: 'Superocean Automatic 42',
    reference: 'A17375E71C1A1',
    caseSizeMm: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Calibre 17',
    complications: ['Date'],
    condition: 'Like New',
    purchaseDate: '2024-07-18',
    purchasePrice: 4200,
    estimatedValue: 4600,
    notes: 'Modernized diver',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
    ownershipStatus: 'Recently Added',
  },
  {
    id: 'breitling-avenger-gmt',
    brand: 'Breitling',
    model: 'Avenger Automatic GMT 45',
    reference: 'A32395101C1A1',
    caseSizeMm: 45,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Calibre 32',
    complications: ['Date', 'GMT'],
    condition: 'Good',
    purchaseDate: '2019-04-09',
    purchasePrice: 3600,
    estimatedValue: 3900,
    notes: 'Large pilot GMT',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'GMT',
    ownershipStatus: 'For Sale',
  },
  {
    id: 'breitling-premier-pistachio',
    brand: 'Breitling',
    model: 'Premier B09 Chronograph 40',
    reference: 'AB0930D31L1P1',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Green',
    movement: 'Breitling B09',
    complications: ['Chronograph'],
    condition: 'Unworn',
    purchaseDate: '2025-01-22',
    purchasePrice: 6900,
    estimatedValue: 7500,
    notes: 'Hand-wound pistachio dial',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#2F5A3A', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Chronograph',
    ownershipStatus: 'Owned',
  },
  {
    id: 'breitling-top-time-deus',
    brand: 'Breitling',
    model: 'Top Time Deus',
    reference: 'A233112A1A1X1',
    caseSizeMm: 41,
    caseMaterial: 'Stainless Steel',
    dialColor: 'White',
    movement: 'Calibre 23',
    complications: ['Chronograph'],
    condition: 'Excellent',
    purchaseDate: '2023-08-26',
    purchasePrice: 4800,
    estimatedValue: 5200,
    notes: 'Retro panda styling',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Vintage',
    ownershipStatus: 'Needs Service',
  },
  {
    id: 'cartier-santos-medium',
    brand: 'Cartier',
    model: 'Santos de Cartier',
    reference: 'WSSA0029',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Calibre 1847 MC',
    complications: ['Date'],
    condition: 'Like New',
    purchaseDate: '2022-05-11',
    purchasePrice: 6200,
    estimatedValue: 6900,
    notes: 'QuickSwitch bracelet',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Integrated Bracelet',
    ownershipStatus: 'Owned',
  },
  {
    id: 'cartier-tank-must-large',
    brand: 'Cartier',
    model: 'Tank Must Large',
    reference: 'WSTA0041',
    caseSizeMm: 37,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Calibre 1847 MC',
    complications: ['Date'],
    condition: 'Excellent',
    purchaseDate: '2021-09-29',
    purchasePrice: 3600,
    estimatedValue: 4100,
    notes: 'Classic cabochon crown',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Dress',
    ownershipStatus: 'For Sale',
  },
  {
    id: 'cartier-ballon-bleu',
    brand: 'Cartier',
    model: 'Ballon Bleu 40',
    reference: 'WSBB0040',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Calibre 1847 MC',
    complications: ['Date'],
    condition: 'Good',
    purchaseDate: '2018-02-05',
    purchasePrice: 4700,
    estimatedValue: 5000,
    notes: 'Roman numeral dial',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Dress',
    ownershipStatus: 'Needs Service',
  },
  {
    id: 'cartier-pasha-41',
    brand: 'Cartier',
    model: 'Pasha de Cartier',
    reference: 'WSPA0013',
    caseSizeMm: 41,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Calibre 1847 MC',
    complications: ['Date'],
    condition: 'Unworn',
    purchaseDate: '2025-03-01',
    purchasePrice: 6800,
    estimatedValue: 7200,
    notes: 'Chain-linked crown cap',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Sport',
    ownershipStatus: 'Recently Added',
  },
  {
    id: 'cartier-santos-dumont',
    brand: 'Cartier',
    model: 'Santos-Dumont XL',
    reference: 'WSSA0032',
    caseSizeMm: 43,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Quartz',
    complications: [],
    condition: 'Fair',
    purchaseDate: '2017-07-07',
    purchasePrice: 2900,
    estimatedValue: 3100,
    notes: 'Large square profile',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Vintage',
    ownershipStatus: 'Owned',
  },
  {
    id: 'grandseiko-snowflake',
    brand: 'Grand Seiko',
    model: 'Heritage Snowflake',
    reference: 'SBGA211',
    caseSizeMm: 41,
    caseMaterial: 'Titanium',
    dialColor: 'White',
    movement: 'Calibre 9R65',
    complications: ['Date', 'Power Reserve'],
    condition: 'Excellent',
    purchaseDate: '2020-12-12',
    purchasePrice: 5200,
    estimatedValue: 5800,
    notes: 'Spring Drive icon',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Dress',
    ownershipStatus: 'Owned',
  },
  {
    id: 'grandseiko-shunbun',
    brand: 'Grand Seiko',
    model: 'Heritage Shunbun',
    reference: 'SBGA413',
    caseSizeMm: 40,
    caseMaterial: 'Titanium',
    dialColor: 'Pink',
    movement: 'Calibre 9R65',
    complications: ['Date', 'Power Reserve'],
    condition: 'Like New',
    purchaseDate: '2024-04-17',
    purchasePrice: 6200,
    estimatedValue: 6900,
    notes: 'Cherry blossom dial',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Sport',
    ownershipStatus: 'Recently Added',
  },
  {
    id: 'grandseiko-sbgm221',
    brand: 'Grand Seiko',
    model: 'Elegance GMT',
    reference: 'SBGM221',
    caseSizeMm: 39,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Ivory',
    movement: 'Calibre 9S66',
    complications: ['Date', 'GMT'],
    condition: 'Good',
    purchaseDate: '2019-09-14',
    purchasePrice: 3900,
    estimatedValue: 4300,
    notes: 'Blue GMT hand',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'GMT',
    ownershipStatus: 'For Sale',
  },
  {
    id: 'grandseiko-white-birch',
    brand: 'Grand Seiko',
    model: 'Evolution 9 White Birch',
    reference: 'SLGH005',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Calibre 9SA5',
    complications: ['Date'],
    condition: 'Unworn',
    purchaseDate: '2025-01-30',
    purchasePrice: 8400,
    estimatedValue: 9100,
    notes: 'High-beat movement',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Sport',
    ownershipStatus: 'Owned',
  },
  {
    id: 'grandseiko-sport-gmt',
    brand: 'Grand Seiko',
    model: 'Sport Quartz GMT',
    reference: 'SBGN017',
    caseSizeMm: 39,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Calibre 9F86',
    complications: ['Date', 'GMT'],
    condition: 'Excellent',
    purchaseDate: '2023-10-08',
    purchasePrice: 2800,
    estimatedValue: 3200,
    notes: '9F quartz precision',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Sport',
    ownershipStatus: 'Needs Service',
  },
]
