import type { CatalogWatch } from '@/types/watch'
import processedManifest from '@/public/watch-assets/processed/manifest.json'
import excludedImagesData from '@/data/excluded-image-ids.json'
import { toStorageUrl } from './watchImages/storageUrl'

type ProcessedManifestEntry = {
  watchId: string
  rawFilename: string
  pngPath: string
  webpPath: string
}

type ExcludedImagesData = {
  ids: Array<{ id: string; reason: string; flaggedAt: string }>
}

const excludedIds = new Set(
  (excludedImagesData as ExcludedImagesData).ids.map(e => e.id),
)

const processedWatchImages = new Map(
  (processedManifest as ProcessedManifestEntry[])
    .filter(entry => !excludedIds.has(entry.watchId))
    .map(entry => [
      entry.watchId,
      {
        // Storage is canonical. Falls back to the local path when
        // NEXT_PUBLIC_SUPABASE_URL is unset (offline dev / CI).
        imageUrl: toStorageUrl(entry.webpPath) ?? entry.webpPath,
        imageTransparentUrl: toStorageUrl(entry.pngPath) ?? entry.pngPath,
        imageSourceUrl: `/watch-assets/raw/${entry.rawFilename}`,
      },
    ])
)

const catalogWatches: CatalogWatch[] = [
  {
    id: 'rolex-126610ln',
    brand: 'Rolex',
    model: 'Submariner Date',
    reference: '126610LN',
    caseSizeMm: 41,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Calibre 3235',
    complications: ['Date'],
    estimatedValue: 12200,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
  },
  {
    id: 'rolex-126710blro',
    brand: 'Rolex',
    model: 'GMT-Master II',
    reference: '126710BLRO',
    caseSizeMm: 40,
    caseMaterial: 'Oystersteel',
    dialColor: 'Black',
    movement: 'Calibre 3285',
    complications: ['Date', 'GMT'],
    estimatedValue: 16900,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'GMT',
  },
  {
    id: 'rolex-116500ln',
    brand: 'Rolex',
    model: 'Cosmograph Daytona',
    reference: '116500LN',
    caseSizeMm: 40,
    caseMaterial: 'Oystersteel',
    dialColor: 'White',
    movement: 'Calibre 4130',
    complications: ['Chronograph'],
    estimatedValue: 27500,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Chronograph',
  },
  {
    id: 'rolex-124270',
    brand: 'Rolex',
    model: 'Explorer',
    reference: '124270',
    caseSizeMm: 36,
    caseMaterial: 'Oystersteel',
    dialColor: 'Black',
    movement: 'Calibre 3230',
    complications: [],
    estimatedValue: 7600,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Field',
  },
  {
    id: 'rolex-126334',
    brand: 'Rolex',
    model: 'Datejust 41',
    reference: '126334',
    caseSizeMm: 41,
    caseMaterial: 'Steel / White Gold',
    dialColor: 'Blue',
    movement: 'Calibre 3235',
    complications: ['Date'],
    estimatedValue: 10800,
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Dress',
  },
  {
    id: 'omega-310-30-42-50-01-001',
    brand: 'Omega',
    model: 'Speedmaster Professional',
    reference: '310.30.42.50.01.001',
    caseSizeMm: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Calibre 3861',
    complications: ['Chronograph'],
    estimatedValue: 7200,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Chronograph',
  },
  {
    id: 'omega-210-30-42-20-03-001',
    brand: 'Omega',
    model: 'Seamaster Diver 300M',
    reference: '210.30.42.20.03.001',
    caseSizeMm: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Calibre 8800',
    complications: ['Date'],
    estimatedValue: 5900,
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
  },
  {
    id: 'omega-220-10-41-21-10-001',
    brand: 'Omega',
    model: 'Seamaster Aqua Terra',
    reference: '220.10.41.21.10.001',
    caseSizeMm: 41,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Green',
    movement: 'Calibre 8900',
    complications: ['Date'],
    estimatedValue: 6100,
    dialConfig: { dialColor: '#2F5A3A', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Sport',
  },
  {
    id: 'omega-220-10-40-20-06-001',
    brand: 'Omega',
    model: 'Railmaster',
    reference: '220.10.40.20.06.001',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Grey',
    movement: 'Calibre 8806',
    complications: [],
    estimatedValue: 4200,
    dialConfig: { dialColor: '#6F6F6F', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Field',
  },
  {
    id: 'omega-130-30-39-21-02-001',
    brand: 'Omega',
    model: 'Constellation Globemaster',
    reference: '130.30.39.21.02.001',
    caseSizeMm: 39,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Calibre 8900',
    complications: ['Date'],
    estimatedValue: 6400,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Dress',
  },
  {
    id: 'patek-philippe-5711-1a-010',
    brand: 'Patek Philippe',
    model: 'Nautilus',
    reference: '5711/1A-010',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Calibre 26-330 S C',
    complications: ['Date'],
    estimatedValue: 50000,
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Integrated Bracelet',
  },
  {
    id: 'patek-philippe-5167a-001',
    brand: 'Patek Philippe',
    model: 'Aquanaut',
    reference: '5167A-001',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Calibre 324 S C',
    complications: ['Date'],
    estimatedValue: 36000,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Sport',
  },
  {
    id: 'patek-philippe-6119r-001',
    brand: 'Patek Philippe',
    model: 'Calatrava',
    reference: '6119R-001',
    caseSizeMm: 39,
    caseMaterial: 'Rose Gold',
    dialColor: 'Ivory',
    movement: 'Calibre 30-255 PS',
    complications: [],
    estimatedValue: 36500,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Dress',
  },
  {
    id: 'patek-philippe-5230p-001',
    brand: 'Patek Philippe',
    model: 'World Time',
    reference: '5230P-001',
    caseSizeMm: 38,
    caseMaterial: 'Platinum',
    dialColor: 'Blue',
    movement: 'Calibre 240 HU',
    complications: ['World Time'],
    estimatedValue: 46500,
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'GMT',
  },
  {
    id: 'patek-philippe-5738r-001',
    brand: 'Patek Philippe',
    model: 'Golden Ellipse',
    reference: '5738R-001',
    caseSizeMm: 39,
    caseMaterial: 'Rose Gold',
    dialColor: 'Blue',
    movement: 'Calibre 240',
    complications: [],
    estimatedValue: 22000,
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Vintage',
  },
  {
    id: 'a-lange-and-sohne-142-031',
    brand: 'A. Lange & Söhne',
    model: 'Zeitwerk',
    reference: '142.031',
    caseSizeMm: 42,
    caseMaterial: 'White Gold',
    dialColor: 'Black',
    movement: 'L043.1',
    complications: ['Power Reserve'],
    estimatedValue: 50000,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Dress',
  },
  {
    id: 'a-lange-and-sohne-191-032',
    brand: 'A. Lange & Söhne',
    model: 'Lange 1',
    reference: '191.032',
    caseSizeMm: 38,
    caseMaterial: 'White Gold',
    dialColor: 'Silver',
    movement: 'L121.1',
    complications: ['Date', 'Power Reserve'],
    estimatedValue: 43000,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Dress',
  },
  {
    id: 'a-lange-and-sohne-205-086',
    brand: 'A. Lange & Söhne',
    model: 'Saxonia Thin',
    reference: '205.086',
    caseSizeMm: 39,
    caseMaterial: 'Pink Gold',
    dialColor: 'Blue',
    movement: 'L093.1',
    complications: [],
    estimatedValue: 24000,
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Dress',
  },
  {
    id: 'a-lange-and-sohne-363-179',
    brand: 'A. Lange & Söhne',
    model: 'Odysseus',
    reference: '363.179',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Grey',
    movement: 'L155.1',
    complications: ['Date', 'Day'],
    estimatedValue: 42000,
    dialConfig: { dialColor: '#6F6F6F', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Integrated Bracelet',
  },
  {
    id: 'a-lange-and-sohne-414-028',
    brand: 'A. Lange & Söhne',
    model: '1815 Chronograph',
    reference: '414.028',
    caseSizeMm: 39,
    caseMaterial: 'Pink Gold',
    dialColor: 'Black',
    movement: 'L951.5',
    complications: ['Chronograph'],
    estimatedValue: 45500,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Chronograph',
  },
  {
    id: 'iwc-iw328203',
    brand: 'IWC',
    model: 'Pilot\'s Watch Mark XX',
    reference: 'IW328203',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Calibre 32111',
    complications: ['Date'],
    estimatedValue: 4900,
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Pilot',
  },
  {
    id: 'iwc-iw329301',
    brand: 'IWC',
    model: 'Big Pilot\'s Watch 43',
    reference: 'IW329301',
    caseSizeMm: 43,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Calibre 82100',
    complications: [],
    estimatedValue: 7600,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Pilot',
  },
  {
    id: 'iwc-iw371606',
    brand: 'IWC',
    model: 'Portugieser Chronograph',
    reference: 'IW371606',
    caseSizeMm: 41,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Calibre 69355',
    complications: ['Chronograph'],
    estimatedValue: 7300,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Chronograph',
  },
  {
    id: 'iwc-iw328901',
    brand: 'IWC',
    model: 'Ingenieur Automatic 40',
    reference: 'IW328901',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Aqua Blue',
    movement: 'Calibre 32111',
    complications: ['Date'],
    estimatedValue: 12600,
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Integrated Bracelet',
  },
  {
    id: 'iwc-iw326805',
    brand: 'IWC',
    model: 'Pilot\'s Watch Automatic Spitfire',
    reference: 'IW326805',
    caseSizeMm: 39,
    caseMaterial: 'Bronze',
    dialColor: 'Brown',
    movement: 'Calibre 32110',
    complications: ['Date'],
    estimatedValue: 4700,
    dialConfig: { dialColor: '#5A3A26', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Pilot',
  },
  {
    id: 'tudor-m79030n-0001',
    brand: 'Tudor',
    model: 'Black Bay 58',
    reference: 'M79030N-0001',
    caseSizeMm: 39,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'MT5402',
    complications: [],
    estimatedValue: 3600,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
  },
  {
    id: 'tudor-m25407n-0001',
    brand: 'Tudor',
    model: 'Pelagos 39',
    reference: 'M25407N-0001',
    caseSizeMm: 39,
    caseMaterial: 'Titanium',
    dialColor: 'Black',
    movement: 'MT5400',
    complications: [],
    estimatedValue: 4500,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
  },
  {
    id: 'tudor-m79830rb-0010',
    brand: 'Tudor',
    model: 'Black Bay GMT',
    reference: 'M79830RB-0010',
    caseSizeMm: 41,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'MT5652',
    complications: ['Date', 'GMT'],
    estimatedValue: 3900,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'GMT',
  },
  {
    id: 'tudor-m79950-0001',
    brand: 'Tudor',
    model: 'Ranger',
    reference: 'M79950-0001',
    caseSizeMm: 39,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'MT5402',
    complications: [],
    estimatedValue: 3100,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Field',
  },
  {
    id: 'tudor-m28600-0005',
    brand: 'Tudor',
    model: 'Royal',
    reference: 'M28600-0005',
    caseSizeMm: 41,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'T603',
    complications: ['Date', 'Day'],
    estimatedValue: 1950,
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Integrated Bracelet',
  },
  {
    id: 'tag-heuer-cbn2011-ba0642',
    brand: 'TAG Heuer',
    model: 'Carrera Chronograph',
    reference: 'CBN2011.BA0642',
    caseSizeMm: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'TH20-00',
    complications: ['Chronograph', 'Date'],
    estimatedValue: 6200,
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Chronograph',
  },
  {
    id: 'tag-heuer-caw211p-fc6356',
    brand: 'TAG Heuer',
    model: 'Monaco',
    reference: 'CAW211P.FC6356',
    caseSizeMm: 39,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Calibre 11',
    complications: ['Chronograph', 'Date'],
    estimatedValue: 5800,
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Vintage',
  },
  {
    id: 'tag-heuer-wbp201f-ba0632',
    brand: 'TAG Heuer',
    model: 'Aquaracer Professional 300',
    reference: 'WBP201F.BA0632',
    caseSizeMm: 43,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Green',
    movement: 'Calibre 5',
    complications: ['Date'],
    estimatedValue: 3400,
    dialConfig: { dialColor: '#2F5A3A', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
  },
  {
    id: 'tag-heuer-wbe511a-ba0650',
    brand: 'TAG Heuer',
    model: 'Autavia GMT',
    reference: 'WBE511A.BA0650',
    caseSizeMm: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Calibre 7',
    complications: ['Date', 'GMT'],
    estimatedValue: 3600,
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'GMT',
  },
  {
    id: 'tag-heuer-wbn2111-ba0639',
    brand: 'TAG Heuer',
    model: 'Carrera Date',
    reference: 'WBN2111.BA0639',
    caseSizeMm: 39,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Calibre 5',
    complications: ['Date'],
    estimatedValue: 2700,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Sport',
  },
  {
    id: 'breitling-ab0138211b1a1',
    brand: 'Breitling',
    model: 'Navitimer B01 Chronograph 43',
    reference: 'AB0138211B1A1',
    caseSizeMm: 43,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Breitling 01',
    complications: ['Chronograph', 'Date'],
    estimatedValue: 8400,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Chronograph',
  },
  {
    id: 'breitling-a17375e71c1a1',
    brand: 'Breitling',
    model: 'Superocean Automatic 42',
    reference: 'A17375E71C1A1',
    caseSizeMm: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Calibre 17',
    complications: ['Date'],
    estimatedValue: 4600,
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
  },
  {
    id: 'breitling-a32395101c1a1',
    brand: 'Breitling',
    model: 'Avenger Automatic GMT 45',
    reference: 'A32395101C1A1',
    caseSizeMm: 45,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Calibre 32',
    complications: ['Date', 'GMT'],
    estimatedValue: 3900,
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'GMT',
  },
  {
    id: 'breitling-ab0930d31l1p1',
    brand: 'Breitling',
    model: 'Premier B09 Chronograph 40',
    reference: 'AB0930D31L1P1',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Green',
    movement: 'Breitling B09',
    complications: ['Chronograph'],
    estimatedValue: 7500,
    dialConfig: { dialColor: '#2F5A3A', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Chronograph',
  },
  {
    id: 'breitling-a233112a1a1x1',
    brand: 'Breitling',
    model: 'Top Time Deus',
    reference: 'A233112A1A1X1',
    caseSizeMm: 41,
    caseMaterial: 'Stainless Steel',
    dialColor: 'White',
    movement: 'Calibre 23',
    complications: ['Chronograph'],
    estimatedValue: 5200,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Vintage',
  },
  {
    id: 'cartier-wssa0029',
    brand: 'Cartier',
    model: 'Santos de Cartier',
    reference: 'WSSA0029',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Calibre 1847 MC',
    complications: ['Date'],
    estimatedValue: 6900,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Integrated Bracelet',
  },
  {
    id: 'cartier-wsta0041',
    brand: 'Cartier',
    model: 'Tank Must Large',
    reference: 'WSTA0041',
    caseSizeMm: 37,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Calibre 1847 MC',
    complications: ['Date'],
    estimatedValue: 4100,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Dress',
  },
  {
    id: 'cartier-wsbb0040',
    brand: 'Cartier',
    model: 'Ballon Bleu 40',
    reference: 'WSBB0040',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Calibre 1847 MC',
    complications: ['Date'],
    estimatedValue: 5000,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Dress',
  },
  {
    id: 'cartier-wspa0013',
    brand: 'Cartier',
    model: 'Pasha de Cartier',
    reference: 'WSPA0013',
    caseSizeMm: 41,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Calibre 1847 MC',
    complications: ['Date'],
    estimatedValue: 7200,
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Sport',
  },
  {
    id: 'cartier-wssa0032',
    brand: 'Cartier',
    model: 'Santos-Dumont XL',
    reference: 'WSSA0032',
    caseSizeMm: 43,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Quartz',
    complications: [],
    estimatedValue: 3100,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Vintage',
  },
  {
    id: 'grand-seiko-sbga211',
    brand: 'Grand Seiko',
    model: 'Heritage Snowflake',
    reference: 'SBGA211',
    caseSizeMm: 41,
    caseMaterial: 'Titanium',
    dialColor: 'White',
    movement: 'Calibre 9R65',
    complications: ['Date', 'Power Reserve'],
    estimatedValue: 5800,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Dress',
  },
  {
    id: 'grand-seiko-sbga413',
    brand: 'Grand Seiko',
    model: 'Heritage Shunbun',
    reference: 'SBGA413',
    caseSizeMm: 40,
    caseMaterial: 'Titanium',
    dialColor: 'Pink',
    movement: 'Calibre 9R65',
    complications: ['Date', 'Power Reserve'],
    estimatedValue: 6900,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Sport',
  },
  {
    id: 'grand-seiko-sbgm221',
    brand: 'Grand Seiko',
    model: 'Elegance GMT',
    reference: 'SBGM221',
    caseSizeMm: 39,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Ivory',
    movement: 'Calibre 9S66',
    complications: ['Date', 'GMT'],
    estimatedValue: 4300,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'GMT',
  },
  {
    id: 'grand-seiko-slgh005',
    brand: 'Grand Seiko',
    model: 'Evolution 9 White Birch',
    reference: 'SLGH005',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Calibre 9SA5',
    complications: ['Date'],
    estimatedValue: 9100,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Sport',
  },
  {
    id: 'grand-seiko-sbgn017',
    brand: 'Grand Seiko',
    model: 'Sport Quartz GMT',
    reference: 'SBGN017',
    caseSizeMm: 39,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Calibre 9F86',
    complications: ['Date', 'GMT'],
    estimatedValue: 3200,
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Sport',
  },
  {
    id: 'oris-d-26-286',
    brand: 'Oris',
    model: 'Big Crown D.26 286 HB-RAG',
    reference: 'D.26 286',
    caseSizeMm: 40,
    lugWidthMm: 20,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Green',
    movement: 'Automatic',
    complications: ['Date'],
    estimatedValue: 1100,
    dialConfig: { dialColor: '#2F5A3A', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Pilot',
  },
  {
    id: 'omega-231-10-42-21-03-003',
    brand: 'Omega',
    model: 'Seamaster Aqua Terra',
    reference: '231.10.42.21.03.003',
    caseSizeMm: 41,
    lugWidthMm: 20,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Co-Axial Master Chronometer',
    complications: ['Date'],
    estimatedValue: 6000,
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Sport',
  },
  {
    id: 'sinn-556-010',
    brand: 'Sinn',
    model: '556.010',
    reference: '556.010',
    caseSizeMm: 38.5,
    lugWidthMm: 20,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Automatic',
    complications: ['Date'],
    estimatedValue: 1200,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Sport',
  },
  {
    id: 'tudor-m79830rb-0001',
    brand: 'Tudor',
    model: 'Black Bay GMT',
    reference: 'M79830RB-0001',
    caseSizeMm: 41,
    lugWidthMm: 22,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Automatic COSC Chronometer',
    complications: ['Date', 'GMT'],
    estimatedValue: 4500,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'GMT',
  },
  {
    id: 'iwc-iw371446',
    brand: 'IWC',
    model: 'Portugieser Chronograph',
    reference: 'IW371446',
    caseSizeMm: 41,
    lugWidthMm: 20,
    caseMaterial: 'Stainless Steel',
    dialColor: 'White',
    movement: 'Automatic',
    complications: ['Chronograph'],
    estimatedValue: 7500,
    dialConfig: { dialColor: '#F5F0E8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Chronograph',
  },
  {
    id: 'tudor-m79830rb',
    brand: 'Tudor',
    model: 'Black Bay GMT',
    reference: 'M79830RB',
    caseSizeMm: 41,
    lugWidthMm: 22,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Master Chronometer',
    complications: ['Date', 'GMT'],
    estimatedValue: 3200,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'GMT',
  },
  {
    id: 'grand-seiko-sbgh267',
    brand: 'Grand Seiko',
    model: 'Hi-Beat 36000',
    reference: 'SBGH267',
    caseSizeMm: 40,
    lugWidthMm: 20,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Automatic Hi-Beat 36000',
    complications: ['Date'],
    estimatedValue: 7000,
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Dress',
  },
  {
    id: 'a-lange-and-sohne-234-026',
    brand: 'A. Lange & Söhne',
    model: '1815 Up/Down',
    reference: '234.026',
    caseSizeMm: 39,
    lugWidthMm: 20,
    caseMaterial: 'White Gold',
    dialColor: 'White',
    movement: 'Manual Winding',
    complications: ['Power Reserve', 'Small Seconds'],
    estimatedValue: 35000,
    dialConfig: { dialColor: '#F5F0E8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Dress',
  },
  {
    id: 'hamilton-h78719553',
    brand: 'Hamilton',
    model: 'Khaki Navy Pioneer',
    reference: 'H78719553',
    caseSizeMm: 41,
    lugWidthMm: 20,
    caseMaterial: 'Stainless Steel',
    dialColor: 'White',
    movement: 'Manual winding',
    complications: ['Small Seconds'],
    estimatedValue: 1000,
    dialConfig: { dialColor: '#F5F0E8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Dress',
  },
  {
    id: 'longines-l3-764-4-50-0',
    brand: 'Longines',
    model: 'Legend Diver',
    reference: 'L3.764.4.50.0',
    caseSizeMm: 39,
    lugWidthMm: 20,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Automatic',
    complications: ['Date'],
    estimatedValue: 3400,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
  },
  {
    id: 'longines-l3-764-4-96-6',
    brand: 'Longines',
    model: 'Legend Diver',
    reference: 'L3.764.4.96.6',
    caseSizeMm: 39,
    lugWidthMm: 20,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Automatic',
    complications: ['Date'],
    estimatedValue: 3400,
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
  },
  {
    id: 'longines-l3-764-4-06-6',
    brand: 'Longines',
    model: 'Legend Diver',
    reference: 'L3.764.4.06.6',
    caseSizeMm: 39,
    lugWidthMm: 20,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Green',
    movement: 'Automatic',
    complications: ['Date'],
    estimatedValue: 3400,
    dialConfig: { dialColor: '#2F5A3A', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
  },
  {
    id: 'longines-l3-764-4-16-6',
    brand: 'Longines',
    model: 'Legend Diver',
    reference: 'L3.764.4.16.6',
    caseSizeMm: 39,
    lugWidthMm: 20,
    caseMaterial: 'Stainless Steel',
    dialColor: 'White',
    movement: 'Automatic',
    complications: ['Date'],
    estimatedValue: 3400,
    dialConfig: { dialColor: '#F5F0E8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Diver',
  },
  {
    id: 'longines-l3-764-4-99-6',
    brand: 'Longines',
    model: 'Legend Diver',
    reference: 'L3.764.4.99.6',
    caseSizeMm: 39,
    lugWidthMm: 20,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Grey Anthracite',
    movement: 'Automatic',
    complications: ['Date'],
    estimatedValue: 3400,
    dialConfig: { dialColor: '#5A5A5A', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
  },
  // ── Discover catalog hydration ─────────────────────────────────────────────
  {
    id: 'tudor-m79540-0006',
    brand: 'Tudor',
    model: 'Black Bay 41',
    reference: 'M79540-0006',
    caseSizeMm: 41,
    lugWidthMm: 22,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Calibre MT5601',
    complications: ['Date'],
    estimatedValue: 3000,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
  },
  {
    id: 'tudor-m79360n-0002',
    brand: 'Tudor',
    model: 'Black Bay Chrono',
    reference: 'M79360N-0002',
    caseSizeMm: 41,
    lugWidthMm: 22,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Calibre MT5813',
    complications: ['Chronograph', 'Date'],
    estimatedValue: 4000,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Chronograph',
  },
  {
    id: 'rolex-124060',
    brand: 'Rolex',
    model: 'Submariner',
    reference: '124060',
    caseSizeMm: 41,
    lugWidthMm: 21,
    caseMaterial: 'Oystersteel',
    dialColor: 'Black',
    movement: 'Calibre 3230',
    complications: [],
    estimatedValue: 9500,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
  },
  {
    id: 'rolex-126710blnr',
    brand: 'Rolex',
    model: 'GMT-Master II',
    reference: '126710BLNR',
    caseSizeMm: 40,
    lugWidthMm: 20,
    caseMaterial: 'Oystersteel',
    dialColor: 'Black',
    movement: 'Calibre 3285',
    complications: ['Date', 'GMT'],
    estimatedValue: 14000,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'GMT',
  },
  {
    id: 'rolex-226570',
    brand: 'Rolex',
    model: 'Explorer II',
    reference: '226570',
    caseSizeMm: 42,
    lugWidthMm: 21,
    caseMaterial: 'Oystersteel',
    dialColor: 'White',
    movement: 'Calibre 3285',
    complications: ['Date', 'GMT'],
    estimatedValue: 9000,
    dialConfig: { dialColor: '#F5F0E8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'GMT',
  },
  {
    id: 'rolex-124300',
    brand: 'Rolex',
    model: 'Oyster Perpetual 41',
    reference: '124300',
    caseSizeMm: 41,
    lugWidthMm: 21,
    caseMaterial: 'Oystersteel',
    dialColor: 'Silver',
    movement: 'Calibre 3230',
    complications: [],
    estimatedValue: 6500,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Sport',
  },
  {
    id: 'rolex-126600',
    brand: 'Rolex',
    model: 'Sea-Dweller',
    reference: '126600',
    caseSizeMm: 43,
    lugWidthMm: 22,
    caseMaterial: 'Oystersteel',
    dialColor: 'Black',
    movement: 'Calibre 3235',
    complications: ['Date'],
    estimatedValue: 12000,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
  },
  {
    id: 'zenith-03-3200-3600-69-m3200',
    brand: 'Zenith',
    model: 'Chronomaster Original',
    reference: '03.3200.3600/69.M3200',
    caseSizeMm: 38,
    lugWidthMm: 19,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'El Primero 3600',
    complications: ['Chronograph', 'Date'],
    estimatedValue: 5500,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Chronograph',
  },
  {
    id: 'jaeger-lecoultre-q3858522',
    brand: 'Jaeger-LeCoultre',
    model: 'Reverso Classic Large',
    reference: 'Q3858522',
    caseSizeMm: 45.6,
    lugWidthMm: 19,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Calibre 822',
    complications: [],
    estimatedValue: 5500,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Dress',
  },
  {
    id: 'jaeger-lecoultre-q1362540',
    brand: 'Jaeger-LeCoultre',
    model: 'Master Ultra Thin Moon',
    reference: 'Q1362540',
    caseSizeMm: 39,
    lugWidthMm: 19,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Calibre 925/1',
    complications: ['Date', 'Moonphase'],
    estimatedValue: 7000,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Dress',
  },
  {
    id: 'longines-l3-810-4-73-6',
    brand: 'Longines',
    model: 'Spirit',
    reference: 'L3.810.4.73.6',
    caseSizeMm: 40,
    lugWidthMm: 20,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Calibre L888.4',
    complications: ['Date'],
    estimatedValue: 1100,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Field',
  },
  {
    id: 'longines-l3-802-4-53-6',
    brand: 'Longines',
    model: 'Spirit Zulu Time',
    reference: 'L3.802.4.53.6',
    caseSizeMm: 42,
    lugWidthMm: 21,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Calibre L844.4',
    complications: ['Date', 'GMT'],
    estimatedValue: 1200,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'GMT',
  },
  {
    id: 'longines-l2-793-4-78-3',
    brand: 'Longines',
    model: 'Master Collection',
    reference: 'L2.793.4.78.3',
    caseSizeMm: 40,
    lugWidthMm: 20,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Calibre L888.5',
    complications: ['Date'],
    estimatedValue: 1500,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Dress',
  },
  {
    id: 'longines-l2-909-4-78-3',
    brand: 'Longines',
    model: 'Master Collection Moonphase',
    reference: 'L2.909.4.78.3',
    caseSizeMm: 40,
    lugWidthMm: 20,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Calibre L899',
    complications: ['Date', 'Moonphase', 'Day'],
    estimatedValue: 1800,
    dialConfig: { dialColor: '#E9E3D8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Dress',
  },
  {
    id: 'grand-seiko-sbgx335',
    brand: 'Grand Seiko',
    model: 'Heritage Quartz',
    reference: 'SBGX335',
    caseSizeMm: 36.5,
    lugWidthMm: 19,
    caseMaterial: 'Stainless Steel',
    dialColor: 'White',
    movement: 'Calibre 9F62',
    complications: ['Date'],
    estimatedValue: 2800,
    dialConfig: { dialColor: '#F5F0E8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Sport',
  },
  {
    id: 'hamilton-h69439931',
    brand: 'Hamilton',
    model: 'Khaki Field Mechanical',
    reference: 'H69439931',
    caseSizeMm: 38,
    lugWidthMm: 20,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Calibre H-50',
    complications: [],
    estimatedValue: 450,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Field',
  },
  {
    id: 'hamilton-h64635555',
    brand: 'Hamilton',
    model: 'Khaki Aviation Pilot Day Date',
    reference: 'H64635555',
    caseSizeMm: 42,
    lugWidthMm: 22,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Calibre H-30',
    complications: ['Date', 'Day'],
    estimatedValue: 650,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Pilot',
  },
  {
    id: 'seiko-spb143',
    brand: 'Seiko',
    model: 'Prospex Alpinist',
    reference: 'SPB143',
    caseSizeMm: 40.5,
    lugWidthMm: 20,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Green',
    movement: 'Calibre 6R35',
    complications: ['Date'],
    estimatedValue: 550,
    dialConfig: { dialColor: '#2F5A3A', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Field',
  },
  {
    id: 'seiko-spb077',
    brand: 'Seiko',
    model: 'Prospex 1965 Diver Reissue',
    reference: 'SPB077',
    caseSizeMm: 39.9,
    lugWidthMm: 20,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Calibre 6R15',
    complications: ['Date'],
    estimatedValue: 550,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
  },
  {
    id: 'seiko-ssk001',
    brand: 'Seiko',
    model: '5 Sports GMT',
    reference: 'SSK001',
    caseSizeMm: 42.5,
    lugWidthMm: 22,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Calibre 4R34',
    complications: ['Date', 'GMT'],
    estimatedValue: 450,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'GMT',
  },
  {
    id: 'seiko-skx007j1',
    brand: 'Seiko',
    model: 'SKX007',
    reference: 'SKX007J1',
    caseSizeMm: 42.5,
    lugWidthMm: 22,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Calibre 7S26',
    complications: ['Date', 'Day'],
    estimatedValue: 300,
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Diver',
  },
  {
    id: 'tissot-t137-407-11-041-00',
    brand: 'Tissot',
    model: 'PRX Powermatic 80',
    reference: 'T137.407.11.041.00',
    caseSizeMm: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Powermatic 80',
    complications: ['Date'],
    estimatedValue: 550,
    dialConfig: { dialColor: '#1E3C62', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
    watchType: 'Integrated Bracelet',
  },
  {
    id: 'orient-fac00004w0',
    brand: 'Orient',
    model: 'Bambino Version 1',
    reference: 'FAC00004W0',
    caseSizeMm: 40.5,
    lugWidthMm: 21,
    caseMaterial: 'Stainless Steel',
    dialColor: 'White',
    movement: 'Calibre F6724',
    complications: ['Date'],
    estimatedValue: 130,
    dialConfig: { dialColor: '#F5F0E8', markerColor: '#1A1410', handColor: '#1A1410' },
    watchType: 'Dress',
  },
]

export const watches: CatalogWatch[] = catalogWatches.map(watch => {
  const imageFields = processedWatchImages.get(watch.id)
  return imageFields ? { ...watch, ...imageFields } : watch
})
