import type { Watch } from '@/types/watch'

export const watches: Watch[] = [
  {
    id: 'longines-ld-white',
    brand: 'Longines',
    model: 'Legend Diver',
    reference: 'L3.764.4.16.6',
    caseSizeMm: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'White',
    movement: 'L888.4 (Auto)',
    complications: ['Date'],
    condition: 'Like New',
    purchaseDate: '2023-09-01',
    purchasePrice: 1180,
    estimatedValue: 1350,
    notes: 'AD purchase, complete set',
    imageUrl: '/watches/longines-05.avif',
    dialConfig: { dialColor: '#F5F0E8', markerColor: '#1A1410', handColor: '#1A1410' },
  },
  {
    id: 'longines-ld-navy',
    brand: 'Longines',
    model: 'Legend Diver',
    reference: 'L3.764.4.96.6',
    caseSizeMm: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Navy Blue',
    movement: 'L888.4 (Auto)',
    complications: ['Date'],
    condition: 'Unworn',
    purchaseDate: '2024-02-01',
    purchasePrice: 1220,
    estimatedValue: 1380,
    notes: 'Birthday gift, unworn',
    imageUrl: '/watches/longines-02.avif',
    dialConfig: { dialColor: '#1B2A4A', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
  },
  {
    id: 'longines-ld-green',
    brand: 'Longines',
    model: 'Legend Diver',
    reference: 'L3.764.4.06.6',
    caseSizeMm: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Forest Green',
    movement: 'L888.4 (Auto)',
    complications: ['Date'],
    condition: 'Excellent',
    purchaseDate: '2022-11-01',
    purchasePrice: 1100,
    estimatedValue: 1450,
    notes: 'Limited run, hard to find',
    imageUrl: '/watches/longines-03.avif',
    dialConfig: { dialColor: '#2A4A2E', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
  },
  {
    id: 'longines-ld-black',
    brand: 'Longines',
    model: 'Legend Diver',
    reference: 'L3.764.4.50.0',
    caseSizeMm: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'L888.4 (Auto)',
    complications: ['Date'],
    condition: 'Good',
    purchaseDate: '2021-06-01',
    purchasePrice: 980,
    estimatedValue: 1250,
    notes: 'Leather strap original',
    imageUrl: '/watches/longines-04.avif',
    dialConfig: { dialColor: '#111111', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
  },
  {
    id: 'longines-ld-grey',
    brand: 'Longines',
    model: 'Legend Diver',
    reference: 'L3.764.4.99.6',
    caseSizeMm: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Grey Anthracite',
    movement: 'L888.4 (Auto)',
    complications: ['Date'],
    condition: 'Excellent',
    purchaseDate: '2023-04-01',
    purchasePrice: 1150,
    estimatedValue: 1340,
    notes: 'Odd dial — love the patina feel',
    imageUrl: '/watches/longines-01.avif',
    dialConfig: { dialColor: '#5A5A5A', markerColor: '#FAF8F4', handColor: '#FAF8F4' },
  },
]
