-- ============================================================
-- Create the `strap-images` storage bucket for admin-curated strap TEMPLATE images
-- (the photorealistic Delugs-style masters generated by scripts/generate-strap-images.ts
-- and surfaced via data/strap-templates.json + the "Quick pick" picker in the Strap Drawer).
--
-- These are curated catalog assets, distinct from per-user strap photos which continue to
-- live in the existing `watch-photos` bucket (user-uploads/{userId}/straps/...).
--
-- Public read so templates render everywhere. Writes are SERVICE-ROLE ONLY: the generation
-- script uploads with the service key (which bypasses RLS), and no anon/authenticated insert
-- policy is created, so end users cannot write template images.
-- ============================================================

insert into storage.buckets (id, name, public)
  values ('strap-images', 'strap-images', true)
  on conflict (id) do nothing;

-- Public read so curated strap templates render everywhere.
drop policy if exists "strap-images: public read" on storage.objects;
create policy "strap-images: public read"
  on storage.objects
  for select
  using (bucket_id = 'strap-images');

-- No insert/update/delete policy on purpose: only the service-role key (used by
-- scripts/generate-strap-images.ts) may write, since it bypasses RLS. End users get
-- read-only access to the curated template library.
